//! Tier-1 chain fixture (ADR-0009): a plain `anvil --load-state`
//! running offline-mode's committed state file (GPv2, tokens, Uniswap V2 at
//! their mainnet addresses — no docker), with the BYOS Escrow deployed through
//! the CREATE2 singleton factory at spawn so its address is stable across
//! runs. Deploy-at-setup is ADR-0009's documented fallback while the contracts
//! churn pre-audit; once they stabilise the contracts get baked into a
//! regenerated state file and this deploy step disappears.

use {
    alloy::{
        network::EthereumWallet,
        node_bindings::{Anvil, AnvilInstance},
        primitives::{Address, B256, Bytes, U256, address, aliases::U48},
        providers::{DynProvider, Provider, ProviderBuilder},
        rpc::types::TransactionRequest,
        signers::local::PrivateKeySigner,
        sol,
        sol_types::SolConstructor,
    },
    anyhow::Context,
    std::io::Write,
};

/// CREATE2 singleton factory (the deterministic-deployment-proxy), present in
/// the offline-mode state at its canonical mainnet address.
const CREATE2_FACTORY: Address = address!("0x4e59b44847b379578588920cA78FbF26c0B4956C");

/// GPv2Settlement, at its mainnet address in the offline-mode state.
pub const GPV2_SETTLEMENT: Address = address!("0x9008D19f58AAbD9eD0D60971565AA8510560ab41");

/// GPv2AllowListAuthentication proxy, at its mainnet address in the
/// offline-mode state.
pub const GPV2_AUTHENTICATOR: Address = address!("0x2c4c28DDBdAc9C5E7055b4C863b72eA0149D8aFE");

// Creation bytecode + constructor, used for deployment only; calls go through
// the `byos_common::contracts` bindings. Generated by `just sync-abis` from the
// pinned byos-contracts submodule, never hand-edited (ADR-0014).
//
// Only the Escrow is vendored: its constructor deploys the TrampolineFactory,
// which embeds the Trampoline creation code. So this one file tracks all three
// contracts — it goes stale on a Trampoline change even though Escrow's own
// source is untouched, and regenerating it shifts every CREATE2 address below.
sol!(EscrowArtifact, "testdata/artifacts/Escrow.json");

sol! {
    #[sol(rpc)]
    interface IGPv2Authentication {
        function isSolver(address prospectiveSolver) external view returns (bool);
    }
}

/// A running tier-1 chain: anvil with the offline-mode state and the BYOS
/// contracts deployed. Anvil is killed when this is dropped.
pub struct Chain {
    anvil: AnvilInstance,
    provider: DynProvider,
    /// The Escrow, at its CREATE2-derived address.
    pub escrow: Address,
    /// The TrampolineFactory the Escrow constructor deployed, read back from
    /// `TRAMPOLINE_FACTORY()`.
    pub trampoline_factory: Address,
}

impl Chain {
    /// Boot the fixture: spawn anvil on a free port with the offline-mode
    /// state, then deploy the Escrow (which deploys its TrampolineFactory)
    /// via CREATE2 from anvil account 0.
    pub async fn spawn() -> anyhow::Result<Self> {
        let state = stripped_state()?;
        let anvil = Anvil::new()
            .port(free_port()?)
            .arg("--load-state")
            .arg(state.path().display().to_string())
            .try_spawn()
            .context("spawning anvil — is foundry installed?")?;

        let signer: PrivateKeySigner = anvil.keys()[0].clone().into();
        let provider = ProviderBuilder::new()
            .wallet(EthereumWallet::from(signer))
            .connect_http(anvil.endpoint_url())
            .erased();

        let accounts = anvil.addresses();
        let roles = EscrowRoles {
            admin: accounts[2],
            operator: accounts[1],
            submitters: vec![accounts[0]],
        };
        let escrow = deploy_escrow(&provider, &roles).await?;
        let trampoline_factory = byos_common::contracts::Escrow::new(escrow, &provider)
            .TRAMPOLINE_FACTORY()
            .call()
            .await
            .context("reading TRAMPOLINE_FACTORY from the deployed Escrow")?;

        Ok(Self {
            anvil,
            provider,
            escrow,
            trampoline_factory,
        })
    }

    pub fn provider(&self) -> &DynProvider {
        &self.provider
    }

    /// The raw anvil instance: keys, addresses, etc. for test setup.
    pub fn anvil(&self) -> &AnvilInstance {
        &self.anvil
    }

    /// The anvil JSON-RPC endpoint.
    pub fn endpoint(&self) -> String {
        self.anvil.endpoint()
    }

    /// The account settlements are sent from (anvil account 0, whitelisted as
    /// a solver in the state's GPv2 Authenticator).
    pub fn solver(&self) -> Address {
        self.anvil.addresses()[0]
    }

    /// Whether [`Self::solver`] is whitelisted in the GPv2 Authenticator.
    pub async fn solver_is_authenticated(&self) -> anyhow::Result<bool> {
        let authenticator = IGPv2Authentication::new(GPV2_AUTHENTICATOR, &self.provider);
        Ok(authenticator.isSolver(self.solver()).call().await?)
    }
}

/// Who holds which role on a fresh Escrow. These are constructor arguments, so
/// they are part of the CREATE2 init code: two deployments with different roles
/// land at different addresses. Tier 1 uses anvil accounts 0/1/2 (see
/// [`Chain::spawn`]); the offline-mode demo uses 3/1/2 so BYOS settles from its
/// own account instead of baseline's.
pub struct EscrowRoles {
    pub admin: Address,
    pub operator: Address,
    /// Accounts granted `SUBMITTER_ROLE` — the ones allowed to settle.
    pub submitters: Vec<Address>,
}

/// Deploy the Escrow through the CREATE2 singleton factory and return its
/// deterministic address.
///
/// Idempotent: with a fixed salt the address is a pure function of the init
/// code, so a second call against a chain that already has the deployment
/// returns the same address without sending a transaction. Tier 1 spawns a
/// fresh anvil every time and never hits that path; the demo's boot recipe
/// re-runs against a live stack and depends on it.
pub async fn deploy_escrow(provider: &DynProvider, roles: &EscrowRoles) -> anyhow::Result<Address> {
    let constructor = EscrowArtifact::constructorCall {
        _adminTransferDelay: U48::from(2 * 24 * 60 * 60),
        _admin: roles.admin,
        _operator: roles.operator,
        _submitters: roles.submitters.clone(),
        _cooldownPeriod: U256::from(24 * 60 * 60),
        _settlement: GPV2_SETTLEMENT,
        _name: "BYOS Escrow".into(),
        _symbol: "BYOS".into(),
    };
    let init_code = [EscrowArtifact::BYTECODE.to_vec(), constructor.abi_encode()].concat();
    let salt = B256::ZERO;
    let escrow = CREATE2_FACTORY.create2_from_code(salt, &init_code);

    if !provider
        .get_code_at(escrow)
        .await
        .context("checking whether the Escrow is already deployed")?
        .is_empty()
    {
        return Ok(escrow);
    }

    // The singleton factory takes `salt ++ init_code` as raw calldata.
    let calldata = [salt.as_slice(), &init_code].concat();
    let receipt = provider
        .send_transaction(
            TransactionRequest::default()
                .to(CREATE2_FACTORY)
                .input(Bytes::from(calldata).into()),
        )
        .await
        .context("sending the Escrow CREATE2 deployment")?
        .get_receipt()
        .await
        .context("awaiting the Escrow CREATE2 deployment receipt")?;
    anyhow::ensure!(receipt.status(), "Escrow CREATE2 deployment reverted");

    Ok(escrow)
}

/// Write a copy of the submodule's state file with the transaction history
/// stripped. Anvil's serialized transaction format changes across versions
/// while the account/block state does not; stripping lets any recent anvil
/// load the fixture without pinning offline-mode's old foundry nightly.
/// Block headers stay — anvil resolves its best block hash from them.
fn stripped_state() -> anyhow::Result<tempfile::NamedTempFile> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../offline-mode/state/anvil-state.json"
    );
    let raw = std::fs::read(path)
        .with_context(|| format!("reading {path} — did you run `git submodule update --init`?"))?;
    let mut state: serde_json::Value =
        serde_json::from_slice(&raw).context("parsing the anvil state file")?;

    let top = state
        .as_object_mut()
        .context("anvil state file is not a JSON object")?;
    top.remove("transactions");
    top.remove("historical_states");
    if let Some(blocks) = top
        .get_mut("blocks")
        .and_then(|blocks| blocks.as_array_mut())
    {
        for block in blocks {
            if let Some(block) = block.as_object_mut() {
                block.insert("transactions".into(), serde_json::Value::Array(vec![]));
            }
        }
    }

    let mut file = tempfile::NamedTempFile::new().context("creating the temp state file")?;
    serde_json::to_writer(&mut file, &state).context("writing the stripped state")?;
    file.flush().context("flushing the stripped state")?;
    Ok(file)
}

/// Ask the OS for a free port. Racy in principle (the port is released before
/// anvil binds it), fine for a test fixture.
fn free_port() -> anyhow::Result<u16> {
    let listener = std::net::TcpListener::bind("127.0.0.1:0").context("probing for a free port")?;
    Ok(listener.local_addr()?.port())
}
